version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: echo srvr | nc localhost 2181 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 5s
      timeout: 10s
      retries: 10

  api:
    build: .
    container_name: news-agent
    ports:
      - "3000:3000"
    environment:
    - NODE_ENV=production
    - KAFKA_BROKER=${KAFKA_BROKER}
    - KAFKA_USERNAME=${KAFKA_USERNAME}
    - KAFKA_PASSWORD=${KAFKA_PASSWORD}
    - KAFKA_TOPIC_NAME="news"
    - KAFKA_GROUP_ID_PREFIX="test-task-"
    depends_on:
      kafka:
        condition: service_healthy